global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # 抓取业务 Hyperf 应用 Metrics
  # 默认: http://192.168.32.50:9771/metrics
  - job_name: netfly-app
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.32.50:9771']
        labels:
          project: skeleton
          instance: comment-sys-service
